name: flutter_cupertino_localizations
description: flutter_cupertino_localizations
version: 1.0.1
author: cRazyx <crz365966834@qq.com>
homepage: https://github.com/crazy365966834/flutter_cupertino_localizations

environment:
 sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
